#I am a member of Amazon and Namecheap's affiliate networks and I may
# earn a commision on anything you get with those links
patreon: faraixyz
custom: 
    - "https://farai.xyz/support"
    - "https://www.amazon.com/?tag=faraixyz-farai.xyz-20"
    - "https://shareasale.com/r.cfm?b=467188&u=2110247&m=46483&urllink=namecheap%2Ecom&afftrack=farai%2Exyz"
